error: no matching constructor for initialization of 'std::ifstream'
```
hardware/interfaces/automotive/ivn_android_device/impl/default/src/IvnAndroidDeviceService.cpp:51:19: error: no matching constructor for initialization of 'std::ifstream' (aka 'basic_ifstream<char>')
   51 |     std::ifstream configStream(mConfigPath);
      |                   ^            ~~~~~~~~~~~
```

Bug: b/353528991
Change-Id: Idddd5d3e38e2d14bb1becdffbc0649b2f3bb5dae
(cherry picked from commit 124b2802a16c9e3a30f78d47afc6ce4739c813af)